# ---------------------------------------
#GitHub Action Part-1 -Basics
#
#Copyleft (c) Vladimir P
#-----------------------------------------

name: My-GitHubActionc_basics


on:
  # Тригер срабатывает при пуше в мастер
  push:
    branches: [ "main" ]
 
jobs:
  my_testing:
   runs-on: ubuntu-latest 

   steps:
   - name: Print Hello Massege
     run : echo "Hello world from testing job" 

  my_deploy:
      runs-on: ubuntu-latest
      
      steps: 
         - name: Print Hello Massege
     run : echo "Hello world from Deploy job"
